### ISSUE TITLE
Update Website

### ISSUE THREAD

**Issue by zhenkangub** [krodik/elostat#48]
As today, Nov 4th the website still shows the result from Oct 3rd to Nov 1st. Since the website is mainly focused on prediction, so maybe you should constantly update it so that it should show some incoming Major League Baseball games.

For the past match results, maybe you could update it as well to show the comparison between the real result and your predicted result. So user will have an idea on how good is your prediction works.

**Comment by krodik** [comment]
Already addressed in Ryver.
